


- hosts: contrail-cloudstack
  user: root
  tasks:
    - yum: name="ant-devel" state=installed
    - yum: name="mysql" state=installed
    - yum: name="mysql-server" state=installed
    - yum: name="mkisofs" state=installed
    - yum: name="MySQL-python" state=installed
    - yum: name="tomcat6" state=installed
    - yum: name="ws-commons-util" state=installed
    - script: ../../auto/RPMS/config-cloudstack.sh
    - service: name=mysqld enabled=yes
    - service: name=mysqld state=started

