##
# Ansible playbook for installing contrail build needed packages on server on Ubuntu 12.04.3 LTS.
#


- hosts: contrail 
  user: root
  tasks:
    ##
    # Apt package installation of required software.
    #
    - name: Install required public repository packages.

    - name: Add apt repository.
      apt_repository: repo=ppa:webupd8team/java state=present


    - name: Oracle java installer
      apt: pkg=oracle-java7-installer state=present


    ##
    # Install ant needed for ifmap-server
    #
    - name: Install ant
      apt: pkg=ant state=present

